// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ordenes.proto

package ordenes

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Orden struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Producto             string   `protobuf:"bytes,2,opt,name=Producto,proto3" json:"Producto,omitempty"`
	Valor                int32    `protobuf:"varint,3,opt,name=Valor,proto3" json:"Valor,omitempty"`
	Destino              string   `protobuf:"bytes,4,opt,name=Destino,proto3" json:"Destino,omitempty"`
	Prioridad            int32    `protobuf:"varint,5,opt,name=Prioridad,proto3" json:"Prioridad,omitempty"`
	Codigo               int32    `protobuf:"varint,6,opt,name=Codigo,proto3" json:"Codigo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Orden) Reset()         { *m = Orden{} }
func (m *Orden) String() string { return proto.CompactTextString(m) }
func (*Orden) ProtoMessage()    {}
func (*Orden) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ea7e50e23b4c6d2, []int{0}
}

func (m *Orden) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Orden.Unmarshal(m, b)
}
func (m *Orden) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Orden.Marshal(b, m, deterministic)
}
func (m *Orden) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Orden.Merge(m, src)
}
func (m *Orden) XXX_Size() int {
	return xxx_messageInfo_Orden.Size(m)
}
func (m *Orden) XXX_DiscardUnknown() {
	xxx_messageInfo_Orden.DiscardUnknown(m)
}

var xxx_messageInfo_Orden proto.InternalMessageInfo

func (m *Orden) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Orden) GetProducto() string {
	if m != nil {
		return m.Producto
	}
	return ""
}

func (m *Orden) GetValor() int32 {
	if m != nil {
		return m.Valor
	}
	return 0
}

func (m *Orden) GetDestino() string {
	if m != nil {
		return m.Destino
	}
	return ""
}

func (m *Orden) GetPrioridad() int32 {
	if m != nil {
		return m.Prioridad
	}
	return 0
}

func (m *Orden) GetCodigo() int32 {
	if m != nil {
		return m.Codigo
	}
	return 0
}

func init() {
	proto.RegisterType((*Orden)(nil), "ordenes.Orden")
}

func init() { proto.RegisterFile("ordenes.proto", fileDescriptor_4ea7e50e23b4c6d2) }

var fileDescriptor_4ea7e50e23b4c6d2 = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x2f, 0x4a, 0x49,
	0xcd, 0x4b, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x66, 0x32,
	0x72, 0xb1, 0xfa, 0x83, 0xd8, 0x42, 0x7c, 0x5c, 0x4c, 0x9e, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a,
	0x9c, 0x41, 0x4c, 0x9e, 0x29, 0x42, 0x52, 0x5c, 0x1c, 0x01, 0x45, 0xf9, 0x29, 0xa5, 0xc9, 0x25,
	0xf9, 0x12, 0x4c, 0x60, 0x51, 0x38, 0x5f, 0x48, 0x84, 0x8b, 0x35, 0x2c, 0x31, 0x27, 0xbf, 0x48,
	0x82, 0x59, 0x81, 0x51, 0x83, 0x35, 0x08, 0xc2, 0x11, 0x92, 0xe0, 0x62, 0x77, 0x49, 0x2d, 0x2e,
	0xc9, 0xcc, 0xcb, 0x97, 0x60, 0x01, 0x6b, 0x80, 0x71, 0x85, 0x64, 0xb8, 0x38, 0x03, 0x8a, 0x32,
	0xf3, 0x8b, 0x32, 0x53, 0x12, 0x53, 0x24, 0x58, 0xc1, 0x7a, 0x10, 0x02, 0x42, 0x62, 0x5c, 0x6c,
	0xce, 0xf9, 0x29, 0x99, 0xe9, 0xf9, 0x12, 0x6c, 0x60, 0x29, 0x28, 0xcf, 0xc8, 0x91, 0x8b, 0x07,
	0xec, 0xb4, 0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0x21, 0x43, 0x2e, 0xde, 0xa0, 0xd4, 0xe4,
	0xd4, 0xcc, 0xb2, 0xd4, 0x14, 0xa8, 0x93, 0xf5, 0x60, 0xbe, 0x02, 0xf3, 0xa5, 0xd0, 0xf8, 0x4a,
	0x0c, 0x49, 0x6c, 0x60, 0xef, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x7e, 0x34, 0xfa, 0x1d,
	0xff, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrdenServiceClient is the client API for OrdenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrdenServiceClient interface {
	ReceivedOrden(ctx context.Context, in *Orden, opts ...grpc.CallOption) (*Orden, error)
}

type ordenServiceClient struct {
	cc *grpc.ClientConn
}

func NewOrdenServiceClient(cc *grpc.ClientConn) OrdenServiceClient {
	return &ordenServiceClient{cc}
}

func (c *ordenServiceClient) ReceivedOrden(ctx context.Context, in *Orden, opts ...grpc.CallOption) (*Orden, error) {
	out := new(Orden)
	err := c.cc.Invoke(ctx, "/ordenes.OrdenService/ReceivedOrden", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrdenServiceServer is the server API for OrdenService service.
type OrdenServiceServer interface {
	ReceivedOrden(context.Context, *Orden) (*Orden, error)
}

// UnimplementedOrdenServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOrdenServiceServer struct {
}

func (*UnimplementedOrdenServiceServer) ReceivedOrden(ctx context.Context, req *Orden) (*Orden, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceivedOrden not implemented")
}

func RegisterOrdenServiceServer(s *grpc.Server, srv OrdenServiceServer) {
	s.RegisterService(&_OrdenService_serviceDesc, srv)
}

func _OrdenService_ReceivedOrden_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Orden)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdenServiceServer).ReceivedOrden(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ordenes.OrdenService/ReceivedOrden",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdenServiceServer).ReceivedOrden(ctx, req.(*Orden))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrdenService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ordenes.OrdenService",
	HandlerType: (*OrdenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceivedOrden",
			Handler:    _OrdenService_ReceivedOrden_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ordenes.proto",
}
